name: Pipeline de CI - Testes e Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_e_lint:
    name: Rodar Testes e Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Rodar lint
        run: npm run lint # Certifique-se que este script existe no seu package.json

      - name: Rodar testes
        run: npm test